# Generated by Django 4.0.2 on 2022-02-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.CharField(default='Not_completed', max_length=255),
        ),
    ]
